
[repo]
kind = "recipe"


[recipe]
author.name = "FIXMESiril?"
author.email = "FIXMESiril?"


[[stage]]

description = "Generate master flat"

# For any camera
auto.for-camera = []

tool = "siril"
input.source = "session" # or auto? prefer ones in session otherwise find by in masters
input.type = "flat" # look in _session_ directories, but look only for flat files

when = "session-config" # run once per session-config
output = "{process_dir}/flat_s{sessionid}_c{sessionconfig}.fits"

context.output_base = "flat"

script = '''
    # Create a sequence from the raw flat frames
    link {output_base} -out={process_dir}
    cd {process_dir}

    # Calibrate the flat frames using master bias
    calibrate {output_base} -bias={strip_extension(bias)}

    # Stack the pre-processed (calibrated) flat frames
    stack pp_{output_base} rej 3 3 -norm=mul -out={flat}
    '''

temporaries = ["{output_base}", "pp_{output_base}"]
