
[[processing.repo.ref]]

# recipe repos contain recpies (identified by name).  When any ag.toml file references
# a recipe the current path of all sources is searched to find that named recipe.

# the standard config includes a few key recipe repos, but interested users or tool
# vendors can define/provide their own

# add a place to find FOO.ag.toml files
url = "http:..."
file = "/foo/blah"



# or inband?


# allow including multiple recipies
[[processing.repo.ref]]

# looks for a file with this name and .py for the code and .toml for the config
# we'll expect that toml file to contain various [[processing.*]] sections which will be loaded at this
# location in the sequence as if they were defined here
by-file = "process-osc-dual-duo"
by-url = "http:..."

