
[author]

# default author info
name = "Bob Dude"
email = "foo@foo.com"
website = "http://mydomain.com/astocruft"
license = "Creative commons etc..."

# define key repos, at first run user will be prompted to select
[[repo.ref]]
file = "/images/masters"

[[repo.ref]]
file = "/images/raws"

[[repo.ref]]
file = "/images/processed"

