
[repo]
kind = "recipe"

# all ag.toml files can optionally contain a version section.  if version of the running astroglue app is out of bounds a warning message will be printed
# to the user and the file will be ignored for future processing.
[recipe.require.version]
min="0.1.0"
max="4.5.8"

[recipe]
author.name = "Kevin Hester"
author.email = "kevinh@geeksville.com"

[[stage]]

description = "Extract OSC dual duo filter Ha, Oiii and Sii channels"
disabled = true # FIXME, debugging later stuff

# FIXME-somehow-specify-what-filternames are used to auto detect this recipe can be used?
# figure out how to support dual duo vs single duo.  Perhaps: the FIRST recipie that matches an auto rule
# is used for any auto-defected defaults.  If an auto match is found it will be saved in the generated starter
# project.toml file.

# non OSC people use names like LRGB or SHO

# for dual duo if we see Sii assume they also have HaOiii
auto.for-filter = ["SiiOiii"]
# for single duo look for this
# auto.for-filter = ["HaOiii"]
auto.for-camera = ["OSC"]

tool = "siril"
when = "session-light" # run once per session-config
output = "FIXME"

# FIXME, bias and flat should have been added to context by two previous stages.  But for now hardwire
# Note: they should not have filename extensions (see strip_extension in the old process.py)
context.bias = '/workspaces/astroglue/images/masters/biases/2025-09-09_stacked.fits'

context.sessionid = "2025-09-16" # FIXME, generate this by looping over all sessions (from outside this file)
context.sessionconfig = "SiiOiii" # FIXME generate this by looping over all session configs
context.light_base = "light_s{sessionid}_c{sessionconfig}"

# FIXME until auto light finding is in
input.source = "path"
input.path = "/workspaces/astroglue/images/from_astroboy/M 27/2025-09-16/LIGHT/*.fit*"

script = '''
    # Create a sequence from the raw light frames, seq file goes to process_dir
    link {light_base} -out={process_dir}
    cd {process_dir}

    # Calibrate the light frames using master bias and flat
    calibrate {light_base} -bias={bias} -flat=flat -cfa -equalize_cfa

    # Remove background gradient on a per-frame basis (generates bkg_pp_light.seq)
    seqsubsky pp_{light_base} 1

    # FIXME only do this step for duo filters (refactor to share common light processing function)
    seqextract_HaOIII bkg_pp_{light_base} -resample=ha
    '''

temporaries = ["FIXME"]

[[stage]]

description = "Stack OSC dual duo filter data, with separate Ha, Oiii and Sii channels"

tool = "python"
when = "session-stack" # run once after all session/session-config processing was done

# if not specified astroglue.py used
# script-file = "script.py"

# or inline python code instead of that function?
#script = '''
#    make_stacked("SiiOiii", "Ha", f"results_00001")
#    ...
#    (moved to script.py)
#    '''