name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # Run the test job on a matrix of OSes. Add 'windows-2025' as requested.
    # Note: if GitHub does not provide a 'windows-2025' runner this job will fail;
    # you can replace it with 'windows-2022' which is commonly available.
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2025, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry (Linux/macOS)
        if: matrix.os != 'windows-2025'
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Install Poetry via pipx (Windows)
        if: matrix.os == 'windows-2025'
        shell: pwsh
        run: |
          # Upgrade pip, install pipx for the current user, ensure pipx path is set,
          # then install Poetry via pipx so Poetry is available for subsequent steps.
          & python -m pip install --upgrade pip
          & python -m pip install --user pipx
          & python -m pipx ensurepath
          & python -m pipx install poetry
          # Compute the user scripts directory (where pipx places executables) and add it to GITHUB_PATH
          $path = (& python -c "import site, os; print(os.path.join(site.getuserbase(), 'Scripts'))")
          Add-Content -Path $env:GITHUB_PATH -Value $path

      #----------------------------------------------
      #       load cached venv if cache exists per https://github.com/marketplace/actions/install-poetry-action
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --with dev

      - name: Run tests
        env:
          SENTRY_ENVIRONMENT: ci
        run: poetry run pytest --cov --cov-report=term --cov-report=xml --junitxml=junit.xml

      - name: Upload coverage artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload junit artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml
          path: junit.xml

  upload:
    # Single upload job that runs once (on linux) after the matrix test job completes
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-xml
          path: .

      - name: Download junit artifact
        uses: actions/download-artifact@v4
        with:
          name: junit-xml
          path: .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}